services:
  tsuattendance:
    image: tsuattendance
    build:
      context: .  # Root context
      dockerfile: Dockerfile  # Path to Dockerfile is at the root level
    ports:
      - "5000:5000"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=AttendanceDB;User=root;Password=root;SslMode=None
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AttendanceDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
